[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@aws-sdk/client-s3", "@aws-sdk/credential-providers"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "astro"
